name: C++ CI (v4)
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y g++ make valgrind libsfml-dev doctest-dev fonts-dejavu-core
      - run: make Main
      - run: make test
      - run: make Gui
